server:
  port: 8080
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      database: 1
      #    password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0
  datasource:
    url: jdbc:postgresql://localhost:15433/more_cloud
    password: password
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true

# Logger Config
logging:
  level:
    com.jds.mc: debug
